--SELECT city.city, country.country FROM city LEFT JOIN country ON city.country_id = country.country_id;
--SELECT payment.payment_id, customer.first_name, customer.last_name FROM payment RIGHT JOIN customer ON payment.customer_id = customer.customer_id;
--SELECT r.rental_id, c.first_name, c.last_name FROM rental r FULL JOIN customer c ON r.customer_id = c.customer_id;
